# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc872ead3d84fd6f78f6b96af69bf5b305e33721e7c7dc4b606297b95f2c1683f2f490325fa52f7fa2ea86e807f50f7016d975ec41f2d0adabbc2fd316ea729e

test:
  secret_key_base: fb430cf48d1b940060dad398792c522abbfb670065797da1b8735426f6f4ef3d9a99ebecdbf7751f2bf009b2ec6c2e8fcb33d2e0561d64568447a26eb5cd1c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
